// Sandbox SSH Gateway - Public client API
// Feature: Edge SSH Gateway (021)
//
// The client-facing slice of the SSH gateway surface: short-lived user SSH
// cert issuance and active-gateway discovery. This is the only SSH gateway
// proto published in the public sandbox SDKs. Control-plane RPCs (gateway
// bootstrap/heartbeat, host enrollment, trust bundle, session-host lookup) and
// policy admin live in ssh_gateway.proto, which is internal-only.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tenki/sandbox/v1/ssh_gateway_client.proto

package sandboxv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/TenkiCloud/tenki-sdk-go/sandbox/internal/proto/tenki/sandbox/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SSHGatewayClientServiceName is the fully-qualified name of the SSHGatewayClientService service.
	SSHGatewayClientServiceName = "tenki.sandbox.v1.SSHGatewayClientService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SSHGatewayClientServiceIssueSandboxSSHCertProcedure is the fully-qualified name of the
	// SSHGatewayClientService's IssueSandboxSSHCert RPC.
	SSHGatewayClientServiceIssueSandboxSSHCertProcedure = "/tenki.sandbox.v1.SSHGatewayClientService/IssueSandboxSSHCert"
	// SSHGatewayClientServiceListActiveSSHGatewaysProcedure is the fully-qualified name of the
	// SSHGatewayClientService's ListActiveSSHGateways RPC.
	SSHGatewayClientServiceListActiveSSHGatewaysProcedure = "/tenki.sandbox.v1.SSHGatewayClientService/ListActiveSSHGateways"
)

// SSHGatewayClientServiceClient is a client for the tenki.sandbox.v1.SSHGatewayClientService
// service.
type SSHGatewayClientServiceClient interface {
	// Cert issuance — called by tenki CLI / SDK on every `tenki sandbox ssh`
	// invocation. Returns a short-lived OpenSSH user cert signed by the active
	// intermediate CA.
	IssueSandboxSSHCert(context.Context, *connect.Request[v1.IssueSandboxSSHCertRequest]) (*connect.Response[v1.IssueSandboxSSHCertResponse], error)
	// Active gateway endpoints — called by tenki CLI / SDK to learn DNS targets.
	ListActiveSSHGateways(context.Context, *connect.Request[v1.ListActiveSSHGatewaysRequest]) (*connect.Response[v1.ListActiveSSHGatewaysResponse], error)
}

// NewSSHGatewayClientServiceClient constructs a client for the
// tenki.sandbox.v1.SSHGatewayClientService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSSHGatewayClientServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SSHGatewayClientServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sSHGatewayClientServiceMethods := v1.File_tenki_sandbox_v1_ssh_gateway_client_proto.Services().ByName("SSHGatewayClientService").Methods()
	return &sSHGatewayClientServiceClient{
		issueSandboxSSHCert: connect.NewClient[v1.IssueSandboxSSHCertRequest, v1.IssueSandboxSSHCertResponse](
			httpClient,
			baseURL+SSHGatewayClientServiceIssueSandboxSSHCertProcedure,
			connect.WithSchema(sSHGatewayClientServiceMethods.ByName("IssueSandboxSSHCert")),
			connect.WithClientOptions(opts...),
		),
		listActiveSSHGateways: connect.NewClient[v1.ListActiveSSHGatewaysRequest, v1.ListActiveSSHGatewaysResponse](
			httpClient,
			baseURL+SSHGatewayClientServiceListActiveSSHGatewaysProcedure,
			connect.WithSchema(sSHGatewayClientServiceMethods.ByName("ListActiveSSHGateways")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sSHGatewayClientServiceClient implements SSHGatewayClientServiceClient.
type sSHGatewayClientServiceClient struct {
	issueSandboxSSHCert   *connect.Client[v1.IssueSandboxSSHCertRequest, v1.IssueSandboxSSHCertResponse]
	listActiveSSHGateways *connect.Client[v1.ListActiveSSHGatewaysRequest, v1.ListActiveSSHGatewaysResponse]
}

// IssueSandboxSSHCert calls tenki.sandbox.v1.SSHGatewayClientService.IssueSandboxSSHCert.
func (c *sSHGatewayClientServiceClient) IssueSandboxSSHCert(ctx context.Context, req *connect.Request[v1.IssueSandboxSSHCertRequest]) (*connect.Response[v1.IssueSandboxSSHCertResponse], error) {
	return c.issueSandboxSSHCert.CallUnary(ctx, req)
}

// ListActiveSSHGateways calls tenki.sandbox.v1.SSHGatewayClientService.ListActiveSSHGateways.
func (c *sSHGatewayClientServiceClient) ListActiveSSHGateways(ctx context.Context, req *connect.Request[v1.ListActiveSSHGatewaysRequest]) (*connect.Response[v1.ListActiveSSHGatewaysResponse], error) {
	return c.listActiveSSHGateways.CallUnary(ctx, req)
}

// SSHGatewayClientServiceHandler is an implementation of the
// tenki.sandbox.v1.SSHGatewayClientService service.
type SSHGatewayClientServiceHandler interface {
	// Cert issuance — called by tenki CLI / SDK on every `tenki sandbox ssh`
	// invocation. Returns a short-lived OpenSSH user cert signed by the active
	// intermediate CA.
	IssueSandboxSSHCert(context.Context, *connect.Request[v1.IssueSandboxSSHCertRequest]) (*connect.Response[v1.IssueSandboxSSHCertResponse], error)
	// Active gateway endpoints — called by tenki CLI / SDK to learn DNS targets.
	ListActiveSSHGateways(context.Context, *connect.Request[v1.ListActiveSSHGatewaysRequest]) (*connect.Response[v1.ListActiveSSHGatewaysResponse], error)
}

// NewSSHGatewayClientServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSSHGatewayClientServiceHandler(svc SSHGatewayClientServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sSHGatewayClientServiceMethods := v1.File_tenki_sandbox_v1_ssh_gateway_client_proto.Services().ByName("SSHGatewayClientService").Methods()
	sSHGatewayClientServiceIssueSandboxSSHCertHandler := connect.NewUnaryHandler(
		SSHGatewayClientServiceIssueSandboxSSHCertProcedure,
		svc.IssueSandboxSSHCert,
		connect.WithSchema(sSHGatewayClientServiceMethods.ByName("IssueSandboxSSHCert")),
		connect.WithHandlerOptions(opts...),
	)
	sSHGatewayClientServiceListActiveSSHGatewaysHandler := connect.NewUnaryHandler(
		SSHGatewayClientServiceListActiveSSHGatewaysProcedure,
		svc.ListActiveSSHGateways,
		connect.WithSchema(sSHGatewayClientServiceMethods.ByName("ListActiveSSHGateways")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tenki.sandbox.v1.SSHGatewayClientService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SSHGatewayClientServiceIssueSandboxSSHCertProcedure:
			sSHGatewayClientServiceIssueSandboxSSHCertHandler.ServeHTTP(w, r)
		case SSHGatewayClientServiceListActiveSSHGatewaysProcedure:
			sSHGatewayClientServiceListActiveSSHGatewaysHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSSHGatewayClientServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSSHGatewayClientServiceHandler struct{}

func (UnimplementedSSHGatewayClientServiceHandler) IssueSandboxSSHCert(context.Context, *connect.Request[v1.IssueSandboxSSHCertRequest]) (*connect.Response[v1.IssueSandboxSSHCertResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.sandbox.v1.SSHGatewayClientService.IssueSandboxSSHCert is not implemented"))
}

func (UnimplementedSSHGatewayClientServiceHandler) ListActiveSSHGateways(context.Context, *connect.Request[v1.ListActiveSSHGatewaysRequest]) (*connect.Response[v1.ListActiveSSHGatewaysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.sandbox.v1.SSHGatewayClientService.ListActiveSSHGateways is not implemented"))
}
