// Sandbox SSH Gateway - Public client API
// Feature: Edge SSH Gateway (021)
//
// The client-facing slice of the SSH gateway surface: short-lived user SSH
// cert issuance and active-gateway discovery. This is the only SSH gateway
// proto published in the public sandbox SDKs. Control-plane RPCs (gateway
// bootstrap/heartbeat, host enrollment, trust bundle, session-host lookup) and
// policy admin live in ssh_gateway.proto, which is internal-only.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tenki/sandbox/v1/ssh_gateway_client.proto

package sandboxv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueSandboxSSHCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session the user wants to SSH to. Cert principal will be "session:<id>".
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// OpenSSH-format public key bytes (e.g. "ssh-ed25519 AAAA..."). Generated
	// ephemerally by the CLI; private key never leaves the laptop.
	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Optional. If unset or > policy max, server caps to policy max.
	RequestedTtl *durationpb.Duration `protobuf:"bytes,3,opt,name=requested_ttl,json=requestedTtl,proto3" json:"requested_ttl,omitempty"`
	// Optional CIDR(s) to bind into critical-options "source-address". When set,
	// SSH refuses cert presentation from any other source IP.
	SourceAddresses []string `protobuf:"bytes,4,rep,name=source_addresses,json=sourceAddresses,proto3" json:"source_addresses,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueSandboxSSHCertRequest) Reset() {
	*x = IssueSandboxSSHCertRequest{}
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSandboxSSHCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSandboxSSHCertRequest) ProtoMessage() {}

func (x *IssueSandboxSSHCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSandboxSSHCertRequest.ProtoReflect.Descriptor instead.
func (*IssueSandboxSSHCertRequest) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescGZIP(), []int{0}
}

func (x *IssueSandboxSSHCertRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IssueSandboxSSHCertRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *IssueSandboxSSHCertRequest) GetRequestedTtl() *durationpb.Duration {
	if x != nil {
		return x.RequestedTtl
	}
	return nil
}

func (x *IssueSandboxSSHCertRequest) GetSourceAddresses() []string {
	if x != nil {
		return x.SourceAddresses
	}
	return nil
}

type IssueSandboxSSHCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenSSH-format certificate (begins with "ssh-ed25519-cert-v01@openssh.com ...").
	SshCert string `protobuf:"bytes,1,opt,name=ssh_cert,json=sshCert,proto3" json:"ssh_cert,omitempty"`
	// Active intermediate CA pubkey for known_hosts pinning.
	CaPub     string                 `protobuf:"bytes,2,opt,name=ca_pub,json=caPub,proto3" json:"ca_pub,omitempty"`
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Hex-encoded uint64. Used for audit and revocation lock-list.
	CertSerial string `protobuf:"bytes,4,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"`
	// Hint to client: re-fetch a fresh cert if connection is older than this.
	RenewalAfter *durationpb.Duration `protobuf:"bytes,5,opt,name=renewal_after,json=renewalAfter,proto3" json:"renewal_after,omitempty"`
	// Resolved permissions for this cert (echo of policy at time of issuance).
	Permissions   *SSHCertPermissions `protobuf:"bytes,6,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSandboxSSHCertResponse) Reset() {
	*x = IssueSandboxSSHCertResponse{}
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSandboxSSHCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSandboxSSHCertResponse) ProtoMessage() {}

func (x *IssueSandboxSSHCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSandboxSSHCertResponse.ProtoReflect.Descriptor instead.
func (*IssueSandboxSSHCertResponse) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescGZIP(), []int{1}
}

func (x *IssueSandboxSSHCertResponse) GetSshCert() string {
	if x != nil {
		return x.SshCert
	}
	return ""
}

func (x *IssueSandboxSSHCertResponse) GetCaPub() string {
	if x != nil {
		return x.CaPub
	}
	return ""
}

func (x *IssueSandboxSSHCertResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *IssueSandboxSSHCertResponse) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

func (x *IssueSandboxSSHCertResponse) GetRenewalAfter() *durationpb.Duration {
	if x != nil {
		return x.RenewalAfter
	}
	return nil
}

func (x *IssueSandboxSSHCertResponse) GetPermissions() *SSHCertPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type SSHCertPermissions struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AllowPty                  bool                   `protobuf:"varint,1,opt,name=allow_pty,json=allowPty,proto3" json:"allow_pty,omitempty"`
	AllowAgentForwarding      bool                   `protobuf:"varint,2,opt,name=allow_agent_forwarding,json=allowAgentForwarding,proto3" json:"allow_agent_forwarding,omitempty"`
	AllowPortForwardingLocal  bool                   `protobuf:"varint,3,opt,name=allow_port_forwarding_local,json=allowPortForwardingLocal,proto3" json:"allow_port_forwarding_local,omitempty"`
	AllowPortForwardingRemote bool                   `protobuf:"varint,4,opt,name=allow_port_forwarding_remote,json=allowPortForwardingRemote,proto3" json:"allow_port_forwarding_remote,omitempty"`
	AllowX11Forwarding        bool                   `protobuf:"varint,5,opt,name=allow_x11_forwarding,json=allowX11Forwarding,proto3" json:"allow_x11_forwarding,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SSHCertPermissions) Reset() {
	*x = SSHCertPermissions{}
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHCertPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHCertPermissions) ProtoMessage() {}

func (x *SSHCertPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHCertPermissions.ProtoReflect.Descriptor instead.
func (*SSHCertPermissions) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescGZIP(), []int{2}
}

func (x *SSHCertPermissions) GetAllowPty() bool {
	if x != nil {
		return x.AllowPty
	}
	return false
}

func (x *SSHCertPermissions) GetAllowAgentForwarding() bool {
	if x != nil {
		return x.AllowAgentForwarding
	}
	return false
}

func (x *SSHCertPermissions) GetAllowPortForwardingLocal() bool {
	if x != nil {
		return x.AllowPortForwardingLocal
	}
	return false
}

func (x *SSHCertPermissions) GetAllowPortForwardingRemote() bool {
	if x != nil {
		return x.AllowPortForwardingRemote
	}
	return false
}

func (x *SSHCertPermissions) GetAllowX11Forwarding() bool {
	if x != nil {
		return x.AllowX11Forwarding
	}
	return false
}

type ListActiveSSHGatewaysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional region filter. Empty = all regions.
	Region        string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSSHGatewaysRequest) Reset() {
	*x = ListActiveSSHGatewaysRequest{}
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSSHGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSSHGatewaysRequest) ProtoMessage() {}

func (x *ListActiveSSHGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSSHGatewaysRequest.ProtoReflect.Descriptor instead.
func (*ListActiveSSHGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescGZIP(), []int{3}
}

func (x *ListActiveSSHGatewaysRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ListActiveSSHGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*ActiveSSHGateway    `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveSSHGatewaysResponse) Reset() {
	*x = ListActiveSSHGatewaysResponse{}
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveSSHGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveSSHGatewaysResponse) ProtoMessage() {}

func (x *ListActiveSSHGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveSSHGatewaysResponse.ProtoReflect.Descriptor instead.
func (*ListActiveSSHGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescGZIP(), []int{4}
}

func (x *ListActiveSSHGatewaysResponse) GetGateways() []*ActiveSSHGateway {
	if x != nil {
		return x.Gateways
	}
	return nil
}

type ActiveSSHGateway struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GatewayId       string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Region          string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	PublicEndpoint  string                 `protobuf:"bytes,3,opt,name=public_endpoint,json=publicEndpoint,proto3" json:"public_endpoint,omitempty"` // e.g. "ssh.us-east-1.tenki.cloud:22"
	MeshEndpoint    string                 `protobuf:"bytes,4,opt,name=mesh_endpoint,json=meshEndpoint,proto3" json:"mesh_endpoint,omitempty"`       // e.g. "<host>:<port>" (reverse-tunnel listener)
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	Healthy         bool                   `protobuf:"varint,6,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Tenki Edge-fronted WebSocket bridge URL for `tenki sandbox ssh`. Empty when
	// the gateway has no Tenki Edge bridge. The SDK constructs the per-session URL
	// by appending "/v1/ssh/<session_id>".
	WsBridgeEndpoint string `protobuf:"bytes,7,opt,name=ws_bridge_endpoint,json=wsBridgeEndpoint,proto3" json:"ws_bridge_endpoint,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ActiveSSHGateway) Reset() {
	*x = ActiveSSHGateway{}
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSSHGateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSSHGateway) ProtoMessage() {}

func (x *ActiveSSHGateway) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSSHGateway.ProtoReflect.Descriptor instead.
func (*ActiveSSHGateway) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescGZIP(), []int{5}
}

func (x *ActiveSSHGateway) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *ActiveSSHGateway) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ActiveSSHGateway) GetPublicEndpoint() string {
	if x != nil {
		return x.PublicEndpoint
	}
	return ""
}

func (x *ActiveSSHGateway) GetMeshEndpoint() string {
	if x != nil {
		return x.MeshEndpoint
	}
	return ""
}

func (x *ActiveSSHGateway) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *ActiveSSHGateway) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ActiveSSHGateway) GetWsBridgeEndpoint() string {
	if x != nil {
		return x.WsBridgeEndpoint
	}
	return ""
}

var File_tenki_sandbox_v1_ssh_gateway_client_proto protoreflect.FileDescriptor

const file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDesc = "" +
	"\n" +
	")tenki/sandbox/v1/ssh_gateway_client.proto\x12\x10tenki.sandbox.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x01\n" +
	"\x1aIssueSandboxSSHCertRequest\x12'\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\tsessionId\x12)\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10 \x18\x80@R\tpublicKey\x12>\n" +
	"\rrequested_ttl\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\frequestedTtl\x123\n" +
	"\x10source_addresses\x18\x04 \x03(\tB\b\xbaH\x05\x92\x01\x02\x10\x10R\x0fsourceAddresses\"\xb3\x02\n" +
	"\x1bIssueSandboxSSHCertResponse\x12\x19\n" +
	"\bssh_cert\x18\x01 \x01(\tR\asshCert\x12\x15\n" +
	"\x06ca_pub\x18\x02 \x01(\tR\x05caPub\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vcert_serial\x18\x04 \x01(\tR\n" +
	"certSerial\x12>\n" +
	"\rrenewal_after\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\frenewalAfter\x12F\n" +
	"\vpermissions\x18\x06 \x01(\v2$.tenki.sandbox.v1.SSHCertPermissionsR\vpermissions\"\x99\x02\n" +
	"\x12SSHCertPermissions\x12\x1b\n" +
	"\tallow_pty\x18\x01 \x01(\bR\ballowPty\x124\n" +
	"\x16allow_agent_forwarding\x18\x02 \x01(\bR\x14allowAgentForwarding\x12=\n" +
	"\x1ballow_port_forwarding_local\x18\x03 \x01(\bR\x18allowPortForwardingLocal\x12?\n" +
	"\x1callow_port_forwarding_remote\x18\x04 \x01(\bR\x19allowPortForwardingRemote\x120\n" +
	"\x14allow_x11_forwarding\x18\x05 \x01(\bR\x12allowX11Forwarding\"6\n" +
	"\x1cListActiveSSHGatewaysRequest\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"_\n" +
	"\x1dListActiveSSHGatewaysResponse\x12>\n" +
	"\bgateways\x18\x01 \x03(\v2\".tenki.sandbox.v1.ActiveSSHGatewayR\bgateways\"\xa7\x02\n" +
	"\x10ActiveSSHGateway\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12'\n" +
	"\x0fpublic_endpoint\x18\x03 \x01(\tR\x0epublicEndpoint\x12#\n" +
	"\rmesh_endpoint\x18\x04 \x01(\tR\fmeshEndpoint\x12F\n" +
	"\x11last_heartbeat_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12\x18\n" +
	"\ahealthy\x18\x06 \x01(\bR\ahealthy\x12,\n" +
	"\x12ws_bridge_endpoint\x18\a \x01(\tR\x10wsBridgeEndpoint2\x87\x02\n" +
	"\x17SSHGatewayClientService\x12r\n" +
	"\x13IssueSandboxSSHCert\x12,.tenki.sandbox.v1.IssueSandboxSSHCertRequest\x1a-.tenki.sandbox.v1.IssueSandboxSSHCertResponse\x12x\n" +
	"\x15ListActiveSSHGateways\x12..tenki.sandbox.v1.ListActiveSSHGatewaysRequest\x1a/.tenki.sandbox.v1.ListActiveSSHGatewaysResponseB\xe5\x01\n" +
	"\x14com.tenki.sandbox.v1B\x15SshGatewayClientProtoP\x01ZTgithub.com/TenkiCloud/tenki-sdk-go/sandbox/internal/proto/tenki/sandbox/v1;sandboxv1\xa2\x02\x03TSX\xaa\x02\x10Tenki.Sandbox.V1\xca\x02\x10Tenki\\Sandbox\\V1\xe2\x02\x1cTenki\\Sandbox\\V1\\GPBMetadata\xea\x02\x12Tenki::Sandbox::V1b\x06proto3"

var (
	file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescOnce sync.Once
	file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescData []byte
)

func file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescGZIP() []byte {
	file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescOnce.Do(func() {
		file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDesc), len(file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDesc)))
	})
	return file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDescData
}

var file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tenki_sandbox_v1_ssh_gateway_client_proto_goTypes = []any{
	(*IssueSandboxSSHCertRequest)(nil),    // 0: tenki.sandbox.v1.IssueSandboxSSHCertRequest
	(*IssueSandboxSSHCertResponse)(nil),   // 1: tenki.sandbox.v1.IssueSandboxSSHCertResponse
	(*SSHCertPermissions)(nil),            // 2: tenki.sandbox.v1.SSHCertPermissions
	(*ListActiveSSHGatewaysRequest)(nil),  // 3: tenki.sandbox.v1.ListActiveSSHGatewaysRequest
	(*ListActiveSSHGatewaysResponse)(nil), // 4: tenki.sandbox.v1.ListActiveSSHGatewaysResponse
	(*ActiveSSHGateway)(nil),              // 5: tenki.sandbox.v1.ActiveSSHGateway
	(*durationpb.Duration)(nil),           // 6: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),         // 7: google.protobuf.Timestamp
}
var file_tenki_sandbox_v1_ssh_gateway_client_proto_depIdxs = []int32{
	6, // 0: tenki.sandbox.v1.IssueSandboxSSHCertRequest.requested_ttl:type_name -> google.protobuf.Duration
	7, // 1: tenki.sandbox.v1.IssueSandboxSSHCertResponse.expires_at:type_name -> google.protobuf.Timestamp
	6, // 2: tenki.sandbox.v1.IssueSandboxSSHCertResponse.renewal_after:type_name -> google.protobuf.Duration
	2, // 3: tenki.sandbox.v1.IssueSandboxSSHCertResponse.permissions:type_name -> tenki.sandbox.v1.SSHCertPermissions
	5, // 4: tenki.sandbox.v1.ListActiveSSHGatewaysResponse.gateways:type_name -> tenki.sandbox.v1.ActiveSSHGateway
	7, // 5: tenki.sandbox.v1.ActiveSSHGateway.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	0, // 6: tenki.sandbox.v1.SSHGatewayClientService.IssueSandboxSSHCert:input_type -> tenki.sandbox.v1.IssueSandboxSSHCertRequest
	3, // 7: tenki.sandbox.v1.SSHGatewayClientService.ListActiveSSHGateways:input_type -> tenki.sandbox.v1.ListActiveSSHGatewaysRequest
	1, // 8: tenki.sandbox.v1.SSHGatewayClientService.IssueSandboxSSHCert:output_type -> tenki.sandbox.v1.IssueSandboxSSHCertResponse
	4, // 9: tenki.sandbox.v1.SSHGatewayClientService.ListActiveSSHGateways:output_type -> tenki.sandbox.v1.ListActiveSSHGatewaysResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tenki_sandbox_v1_ssh_gateway_client_proto_init() }
func file_tenki_sandbox_v1_ssh_gateway_client_proto_init() {
	if File_tenki_sandbox_v1_ssh_gateway_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDesc), len(file_tenki_sandbox_v1_ssh_gateway_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenki_sandbox_v1_ssh_gateway_client_proto_goTypes,
		DependencyIndexes: file_tenki_sandbox_v1_ssh_gateway_client_proto_depIdxs,
		MessageInfos:      file_tenki_sandbox_v1_ssh_gateway_client_proto_msgTypes,
	}.Build()
	File_tenki_sandbox_v1_ssh_gateway_client_proto = out.File
	file_tenki_sandbox_v1_ssh_gateway_client_proto_goTypes = nil
	file_tenki_sandbox_v1_ssh_gateway_client_proto_depIdxs = nil
}
